### ISSUE TITLE
Thoughts on translating docs?

### ISSUE THREAD

**Issue by bmcminn** [AlpenglowTheme/alpenglow-theme#11]
Probably don't have a significant need around this yet, but we could look into translating the `README` doc into its various translations. (eg: `README-RU.md`, `README-DE.md`, etc)

**Comment by egeerardyn** [comment]
It would certainly be nice to have translations, but I don't think there is any substantial demand for this.

I have had a quick look around, and it seems that Sublime Text is not localized (on Package Control I find [1 localization package](https://packagecontrol.io/browse/labels/localization): Chinese/Japanse). So I am quite certain that 99% of ST users can manage to read everything in English.

Apart from that, I think we are a very small team and translating documentation (and keeping all languages updated at all times), would require more effort than it it worth, IMHO.

**Comment by egeerardyn** [comment]
I'm closing this: there is no need for translations (yet? ever?). If we decide otherwise in the future, we can always re-open (or start a new issue).
