### ISSUE TITLE
Logo for AlpenGlow organization?

### ISSUE THREAD

**Issue by egeerardyn** [AlpenglowTheme/alpenglow-theme#13]
I think the generated icon for the Alpenglow organization looks ugly. If there is somebody with some artistic talent to create a logo or applicable photo, I would certainly appreciate that.

Just an idea, maybe an artistic rendering of a mountain (the Matterhorn?) with some alpenglow. Maybe better even if the colors of the theme are used?

**Comment by vikjam** [comment]
Here's a quick stab that could fill the spot until folks come up with something cooler. I used the background from the Afterglow theme page.

![example](https://cloud.githubusercontent.com/assets/1154799/14540227/fa927bfc-0251-11e6-9e04-7d6523992b1a.png)

**Comment by egeerardyn** [comment]
I just love it. Sleek!

**Comment by demartini** [comment]
Loved it. <3

**Comment by vikjam** [comment]
Aww shucks, happy to hear people like it!

**Comment by egeerardyn** [comment]
Given the overwhelmingly positive replies, this can be closed. Thanks a lot!
![screen shot 2016-04-14 at 22 43 52](https://cloud.githubusercontent.com/assets/177360/14543022/659a6dde-0292-11e6-8ff2-b645aef5c2a5.png)
