### ISSUE TITLE
Incorporate gitgutter

### ISSUE THREAD

**Issue by egeerardyn** [AlpenglowTheme/alpenglow-theme#18]
This is implemented by @cannikin in YabataDesign/afterglow-theme#121, but we can probably port his changes quite easily or maybe he is even willing to issue a PR here instead?

**Comment by vikjam** [comment]
I thought Afterglow (and hence Alpenglow) already had GitGutter support (listed as such on the [GitGutter repository](https://github.com/jisaacks/GitGutter)).

If you take a look at the [main color scheme](https://github.com/AlpenglowTheme/alpenglow-theme/blob/master/Alpenglow.tmTheme), it looks like it's supported. I guess it's missing in the Twilight and Monokai schemes?

**Comment by cannikin** [comment]
Hello! Yeah I added it to the Twilight theme specifically. What's the difference between alpenglow and afterglow anyway? Am I not using the same theme as the cool kids??

**Comment by egeerardyn** [comment]
@cannikin The difference is that AlpenGlow has a more active community (though a bit young), whereas Afterglow has not been updated for months.

**Comment by vikjam** [comment]
Interested in closing out this issue? I believe we should have GitGutter support in all the themes now.

**Comment by egeerardyn** [comment]
@vikjam: true, this can be closed.
