### ISSUE TITLE
Bold and Italics Support

### ISSUE THREAD

**Issue by vikjam** [AlpenglowTheme/alpenglow-theme#21]
There doesn't seem to be bold and italics support for bold and italics keywords in Sublime. For example, this is how the code is currently rendered:

Markdown: ![md-before](https://cloud.githubusercontent.com/assets/1154799/14873417/2d3b3bb2-0cc4-11e6-8b5f-72346f4a81f3.png)
LaTeX: ![tex-before](https://cloud.githubusercontent.com/assets/1154799/14873431/58251348-0cc4-11e6-9c85-0a2e5cfeb720.png)

I'm working on a pull request so that it appears like this:
Markdown: ![tex-after](https://cloud.githubusercontent.com/assets/1154799/14873418/2d420014-0cc4-11e6-8fa1-2b54365e292d.png)
LaTeX: ![md-after](https://cloud.githubusercontent.com/assets/1154799/14873443/7e2c2284-0cc4-11e6-9e8b-f3f11264f82f.png)

You can checkout the changes in [this fork](https://github.com/vikjam/alpenglow-theme). If you have any comments, let me know!

**Comment by egeerardyn** [comment]
Closed by #22.
