### ISSUE TITLE
Need to submit package to PackageControl.io

### ISSUE THREAD

**Issue by bmcminn** [AlpenglowTheme/alpenglow-theme#3]
https://packagecontrol.io/docs/submitting_a_package#Step_2

**Comment by egeerardyn** [comment]
Before we do so, perhaps we should also reset the version number and remove the contents of `./messages` to reflect this as well?

**Comment by bmcminn** [comment]
That makes sense. Wanted to discuss the versioning strategy, since we technically have all the Git history from Afterglow. May as well reset the version history for the sake of the repository and the Package Control listing.

**Comment by ntwb** [comment]
It would be great to get this published, I'm still using Afterglow and will gladly switch once this is published 🎉 

Sadly I've little time to dedicate to contributing to another open source project though 😖

**Comment by egeerardyn** [comment]
Actions taken:
- grouped all old messages into 0.9.9 message
- issued pre-release 0.9.9
- submitted package, see wbond/package_control_channel#5517

Actions still pending (in order!):
- [x] make a changelog for v1.0.0 to document our changes on top of Afterglow and release it
- [x] wait for wbond/package_control_channel#5517 to be merged
- [x] revert 2e9e1a1d3d32bd0762a197900dcbcdba6f8f1d65
- [x] close this issue
