### ISSUE TITLE
Modified tab bottom border brightness inconsistency

### ISSUE THREAD

**Issue by Syden10** [AlpenglowTheme/alpenglow-theme#42]
![screen shot 2017-08-01 at 11 20 48 pm](https://user-images.githubusercontent.com/12631452/28855158-7ab2e38c-7711-11e7-89e6-0602dca1fa36.png)

![screen shot 2017-08-01 at 11 21 04 pm](https://user-images.githubusercontent.com/12631452/28855168-92ff7cde-7711-11e7-9a37-5a7a38b68992.png)

Any clue what could be causing this? Issue present on both afterglow and alpenglow, any color option.

Tried:

- Reinstalling both themes, restarting sublime.

- Different color syntax, different tab sizes. 

macOS 10.12.6 (no retina) - Dev Build 3142

Thank you for your time, amazing theme!

**Comment by bmcminn** [comment]
My guess is current file selection highlight? Haven't used the theme in quite a while, so may have to reload it and see this behavior in action.

**Comment by Syden10** [comment]
Seems to be related to dev builds, it's like there is a subtle shadow between the end of the tab and the coding section, downgraded to stable 3126 and did the trick. Thanks though, regards.

![screen shot 2017-08-04 at 11 15 24 pm](https://user-images.githubusercontent.com/12631452/28992128-ef2d9cc4-796a-11e7-99e0-71872f013590.png)

**Comment by Syden10** [comment]
Please consider re-opening, after today's update (3143) issue is back, so probably something related to sublime. Issue is visible on both windows and mac machines. Thanks for your time.

**Comment by ivansorlov** [comment]
I noticed that this depends on the width of the tab. If the file name on the tab is less than 15 characters, then the line is pale.
