### ISSUE TITLE
Missing icons and some confusions on icons

### ISSUE THREAD

**Issue by shivapoudel** [AlpenglowTheme/alpenglow-theme#46]
![capture](https://user-images.githubusercontent.com/3774827/33233149-e477f306-d239-11e7-8393-9ece4607e1c7.PNG)

**Missing icons for:**
- CSV file extensions - See `dummy-products.csv, sample-tax-rates.csv `
- POT file extensions - See `woocommerce.pot`
- NEON file extensions - See `apigen.neon`

**Missing icons for some configurations files and showing cog icon:**
- `.babelrc` - [Babel configuration file](https://babeljs.io/)
- `.jshintrc` - [JSHint configuration file](http://jshint.com/)
- `.stylelintrc` - [Stylelint configuration file](https://stylelint.io/)
- `Gulpfile.js` - Show [GulpJS](https://gulpjs.com/) - there is image but not showing.
- `Gruntfile.js` - Show [GruntJS](https://gruntjs.com/) - there is image but not showing.

**Confused icons**
- `.editorconfig` - [EditorConfig configuration file](http://editorconfig.org/)
- `composer.json` - [Composer configuration file](https://getcomposer.org/) - Different icon showing now for `composer.lock`

**Comment by vikjam** [comment]
In order to keep up with icon requests, perhaps Alpenglow should enable [A File Icon](https://github.com/ihodev/a-file-icon).
